name: Aviator 30s Tracker
on:
  workflow_dispatch: # دستی چلانے کا آپشن
  schedule:
    - cron: '0 */1 * * *'  # ہر گھنٹے میں ایک بار (00 منٹ پر)

jobs:
  track-aviator:
    runs-on: ubuntu-latest  # مفت Linux سرور
    timeout-minutes: 60     # ہر جاب 60 منٹ تک چلے گی
    
    steps:
    # مرحلہ 1: کوڈ ڈاؤن لوڈ کریں
    - name: Checkout code
      uses: actions/checkout@v4
      
    # مرحلہ 2: Python سیٹ اپ کریں
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # Python ورژن
      
    # مرحلہ 3: لائبریریز انسٹال کریں
    - name: Install dependencies
      run: pip install -r requirements.txt
      
    # مرحلہ 4: سکرپٹ چلائیں
    - name: Run Continuous Tracker
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}  # خفیہ ٹوکن
        CHAT_ID: ${{ secrets.CHAT_ID }}      # خفیہ چیٹ آئی ڈی
      run: python main.py  # مین سکرپٹ چلائیں
